version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=quizapp
      - POSTGRES_USER=quizappuser
      - POSTGRES_PASSWORD=123456789

  web:
    build: .
    restart: always
    env_file:
      - .env.local
    command: bash -c "python3 manage.py makemigrations; python3 manage.py migrate --noinput; python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8060:8000
    links:
      - db
    depends_on:
      - db
