version: '3'

services:
  db:
    image: postgres

  web:
    image: app
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8050:8000
    links:
      - db
    depends_on:
      - migration

  migration:
    build: .
    image: app
    command: bash -c "python3 manage.py makemigrations; python3 manage.py migrate --noinput"
    volumes:
      - .:/code
    links:
      - db
