version: '2'

services:
  proxy:
    build: ./proxy
    restart: always
    ports:
      - ${HOST_PORT}:80
    links:
      - web

  web:
    build: ./quiz_app
    restart: always
    expose:
      - "5000"
    env_file:
      - .env
    command: bash -c "python3 manage.py makemigrations; python3 manage.py migrate --noinput; python3 manage.py runserver 0.0.0.0:5000"
    volumes:
      - ./quiz_app:/code
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}